<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>

<html>
<head>
<title>Executiveweb Communications - Corporate Web and E-commerce design</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta http-equiv="Page-Enter" content="revealTrans(Duration=2.0,Transition=12)">
<style type="text/css">
<!--
a:visited {  font-family: Verdana, Arial, Helvetica, sans-serif; font-size: xx-small; color: #000000; text-decoration: none}
a:hover {  font-family: Verdana, Arial, Helvetica, sans-serif; font-size: xx-small; font-weight: bold; color: #FFCC33; text-decoration: none}
a:link {  font-family: Verdana, Arial, Helvetica, sans-serif; font-size: xx-small; font-weight: bold; color: #000000; text-decoration: none}

-->
</style>
<meta name="description" content="Corporate web design, online marketing, e-commerce development, and database driven design. Based outside of Toronto we develop solutions for clients worldwide.">
<meta name="keywords" content="Corporate web design, e-commerce development, database driven, shopping cart, credit card, secure transactions, high speed hosting, web page, online marketing, graphic design, illustration, logo, store front, public relations, programming, consulting">
</head>

<body bgcolor="#666666" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<?php echo $this->layout()->content; ?>
</body>
</html>

  
